### ISSUE TITLE
WPS Get and Post request examples?

### ISSUE THREAD

**Issue by cehbrecht** [ESGF/esgf-compute-api#48] opened 2019-02-20 15:34 UTC
I have started to collect *WPS GET* request examples for the ESGF API, but the *WPS execute* request fails. See the examples in this notebook:

https://nbviewer.jupyter.org/github/cehbrecht/jupyterlab-notebooks/blob/master/esgf-cwt-demo/cwt-urls.ipynb

I have not tried *WPS POST* requests yet.

**Comment by jasonb5** [comment] 2019-02-28 19:18
I think the problem is how the datainputs parameter is formatted. Here's an [example](https://github.com/ESGF/esgf-compute-api/blob/devel/docs/source/cwt.compat.rst#full-examples)

On a sidenote the newest devel version of esgf-compute-api is using OWSLib now as well.

**Comment by cehbrecht** [comment] 2019-03-04 14:20
@jasonb5 the `DataInputs` parameter for a WPS Get request is standardized. Here an example, though it is hard to read:
http://geoprocessing.info/wpsdoc/1x0ExecuteGET

**Comment by jasonb5** [comment] 2019-03-14 16:56
@cehbrecht You're correct, that format is incorrect. I based the original GET implementation off of this [document](https://docs.google.com/document/d/1GSLwSJPUCfs-ZrYCG1n7BcWyldvb4pT9nYD3zkPCwao/edit?usp=sharing), which is incorrect, and it was never revisited after it's initial implementation.

I've created an issue to fix this in our server implementation ESGF/esgf-compute-wps#195, closing this as it's a service issue.

**Closed as completed by jasonb5** 2019-03-14 16:56 UTC
Labels: kind/question
